Neuralnet
mhw32/Adaware pull request #3
Opened 2016-09-18 17:48 UTC by mhw32

- 99% accuracy. 
- finished linking all parts of disambiguator.

2016-09-18 19:21 UTC, kennyhlam commented on disambiguator.py
> +    new_labels = np.zeros((eos_idx.shape[0], labels.shape[1]))
I'm not sure what you're going for here. `labels` is a 1-D array when you call it from `create_features_labels`, so `.shape[1]` fails

2016-09-18 19:27 UTC, kennyhlam commented on disambiguator.py
> +        ctd.get_auc(y_test[:, 1], np.exp(y_pred))))
Why's it `y_test[:, 1]`, shouldn't it be 0? Isn't it just a 1-D array? This depends on what you were hoping to go for in the `make_grams`, so could be a no-op

2016-09-18 19:30 UTC, kennyhlam requested changes
just some questions, and the `make_grams` fails for me

2016-09-18 19:30 UTC, kennyhlam commented on disambiguator.py
> +    tag_counts = defaultdict(lambda: np.zeros(num_tags))
lol, remove

2016-09-18 19:30 UTC, kennyhlam commented on disambiguator.py
> +    mapper["NC"] = [ARTICLE]                      # cited word (hypenated after regular tag)
this isn't an article right?

2016-09-18 19:30 UTC, kennyhlam commented on create_toy_data.py
> +def get_auc(outputs, probas):
does this really belong in create_toy_data? it's just some auxillary function to calculate the goodness of your probabilities

2016-09-18 19:36 UTC, kennyhlam commented
Also, we're slowly but surely building more files that are going into `storage/`, based on the number of parameters we're having to store. For now, it's still pretty easy and manageable to generate them, but I'm wondering if we should start a `datagen` folder with binaries (or one really big one) to generate all our parameters in turn. I predict we'll have an increasing number of parameters we'll want to store in the future, especially if we try other techniques.

The generation of our parameters also requires a strict ordering (must write/load tag order before making k-grams around EOS punctuation). I've personally just been shoving stuff the steps into `workspace.py`, just cause it's there, but I don't know what you're thinking going forward.

2016-09-22 07:06 UTC, kennyhlam commented on create_toy_data.py
> +
So by switching to the punkt tokenizer, we're getting more "bad splits":

reading: datasets/brown/raw/cl11
found an item with no tag: M.E.

reading: datasets/brown/raw/cj24
found an item with no tag: B.
found an item with no tag: B.

reading: datasets/brown/raw/cj58
found an item with no tag: B.

reading: datasets/brown/raw/cj73
found an item with no tag: '?

reading: datasets/brown/raw/cf29
found an item with no tag: TR.

reading: datasets/brown/raw/ca15
found an item with no tag: U.

reading: datasets/brown/raw/cd03
found an item with no tag: B.B.C.

reading: datasets/brown/raw/ca40
found an item with no tag: A.A.U.

2016-09-23 08:50 UTC, kennyhlam commented
I looked at the neuralnet stuff, I don't know what the exact math that's supposed to happen is, but I read all the code and it looks reasonable.

I made https://github.com/mhw32/Adaware/pull/7

If you're good with that, I'm good to merge everything into master.

2016-09-29 21:25 UTC, mhw32 commented on disambiguator.py
> +    tag_counts = defaultdict(lambda: np.zeros(num_tags))
deleted.

2016-09-29 21:26 UTC, mhw32 commented on disambiguator.py
> +    mapper["NC"] = [ARTICLE]                      # cited word (hypenated after regular tag)
Added as [OTHERS]

2016-09-29 21:26 UTC, mhw32 commented on disambiguator.py
> +    new_labels = np.zeros((eos_idx.shape[0], labels.shape[1]))
added back in the get_dummies(...) call

2016-09-29 21:26 UTC, mhw32 commented on disambiguator.py
> +        ctd.get_auc(y_test[:, 1], np.exp(y_pred))))
added back in the get_dummies(...) call

2016-09-29 21:28 UTC, mhw32 commented on create_toy_data.py
> +def get_auc(outputs, probas):
moved to separate file called "metrics"

2016-09-29 21:30 UTC, mhw32 commented on create_toy_data.py
> +
Hmm... well what this tell me is that we need a better labeling system... Maybe we can find a dataset somewhere

2016-09-29 21:31 UTC, mhw32 commented
Pushed simple changes. Let me know if we are good to go. @kennyhlam

2016-10-12 06:33 UTC, kennyhlam approved these changes

2016-10-16 03:05 UTC, merged